#!/bin/bash

(
    cd /srv/salt_upstream
    [ -d .git ] || \
        git clone git@github.com:buddycloud/buddycloud-vm.git . || \
        git clone https://github.com/buddycloud/buddycloud-vm.git .
    git pull
)
(
    cd /srv/salt_local
    [ -d .git ] && git pull
)
