base:
  '*':
    - sanity
    - time
    - sssd
    - groups
    - users
    - sudoers
    - certificates
    - node 
    - nginx
    - sun-java
    - tigase-server
    - buddycloud-server-java
    - buddycloud-media-server
    - buddycloud-pusher
    - buddycloud-hosting
    - buddycloud-http-api
    - buddycloud-webapps
    - buddycloud-http-api
    - node
    - postgres
    - nginx
    - ruby
    - mumble-server
    - buddycloud-downloads
    - buddycloud-angular-app
    - buddycloud-ddns
