base:
  '*':
    - base.sanity
    - saltstack
    - packages
    - kernel
    - motd
    - wheel
    - users
    - iptables
    - bind
    - postgres
    - node
    - prosody
    - nginx
    - buddycloud-server-java
    - buddycloud-media-server
    - buddycloud-http-api
    - wifi-chat
    - webclient
    - webhook-deployer
