#!/bin/bash                                                                                                            
                                                                                                                       
# webclient                                                                                                            
(                                                                                                                      
    # get the code                                                                                                     
    cd /usr/src                                                                                                        
    rm -rf buddycloud-webclient                                                                                        
    git clone git://github.com/buddycloud/buddycloud-webclient.git                                                     
    cd buddycloud-webclient
    git submodule update --init

    # build it
    npm install .
    rm -f build.tar.gz
    [ -d node_modules/bufferstream/node_modules/buffertools/build/Release/ ] || (
        cp -r node_modules/bufferstream/node_modules/buffertools/build/{Debug,Release}
    )
    ./node_modules/.bin/coffee ./src/build/server.coffee --build

    # roll it
    cd /srv/http/
    tar -xzf /usr/src/buddycloud-webclient/build.tar.gz
    rm ./config.js
    ln -s /etc/buddycloud/web-config.js ./config.js
    /etc/init.d/apache2 reload
)

# server component
(
    apt-get install libpq-dev libexpat1-dev

    # get the code
    cd /usr/src
    rm -rf buddycloud-server
    git clone git://github.com/buddycloud/buddycloud-server.git
    cd buddycloud-server

    # build it
    npm install .
)
# switch server
/etc/init.d/prosody stop
killall lua
killall node
killall buddycloud-server
( cd /usr/src/buddycloud-server ; tar -cSsp . ) | (cd /srv/xmpp-component/ ; tar -xSsp )
cd /srv/xmpp-component/
rm -rf /srv/xmpp-component/lib/node_modules/buddycloud-server/node_modules/node-stringprep
ln -s /usr/lib/node_modules/node-stringprep /srv/xmpp-component/lib/node_modules/buddycloud-server/node_modules/node-stringprep
/usr/bin/psql --user buddycloud --host 127.0.0.1 buddycloud-server -f /srv/xmpp-component//lib/node_modules/buddycloud-server/postgres.sql
rm /srv/xmpp-component/lib/node_modules/buddycloud-server/config.js
ln -s /etc/buddycloud/component-config.js /srv/xmpp-component/lib/node_modules/buddycloud-server/config.js

/etc/init.d/prosody start
/etc/init.d/buddycloud-component start
/etc/init.d/apache2 restart

