echo #JDBC_DB_HOST#:#JDBC_DB_PORT#:#TIGASE_JDBC_DB_NAME#:#TIGASE_JDBC_DB_USER#:#TIGASE_JDBC_DB_PASS# > ~/.pgpass
chmod 600 ~/.pgpass
psql -w -U #TIGASE_JDBC_DB_USER# -d #TIGASE_JDBC_DB_NAME# -h #JDBC_DB_HOST# -p #JDBC_DB_PORT# -c "SELECT TigAddUserPlainPw('#MEDIA_XMPP_CLIENT_USER#@#MEDIA_XMPP_CLIENT_DOMAIN#', '#MEDIA_XMPP_CLIENT_PASSWORD#');" | true
rm ~/.pgpass
